// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_database_instance

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DatabaseInstanceDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"database_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the database.",
				MarkdownDescription: "The name of the database.",
			},
			"instance": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"hostname": schema.StringAttribute{
						Computed:            true,
						Description:         "The DNS hostname used for client libSQL and HTTP connections (specific to this instance only).",
						MarkdownDescription: "The DNS hostname used for client libSQL and HTTP connections (specific to this instance only).",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The name of the instance (location code).",
						MarkdownDescription: "The name of the instance (location code).",
					},
					"region": schema.StringAttribute{
						Computed:            true,
						Description:         "The location code for the region this instance is located.",
						MarkdownDescription: "The location code for the region this instance is located.",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "The type of database instance this, will be `primary` or `replica`.",
						MarkdownDescription: "The type of database instance this, will be `primary` or `replica`.",
					},
					"uuid": schema.StringAttribute{
						Computed:            true,
						Description:         "The instance universal unique identifier (UUID).",
						MarkdownDescription: "The instance universal unique identifier (UUID).",
					},
				},
				CustomType: InstanceType{
					ObjectType: types.ObjectType{
						AttrTypes: InstanceValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"instance_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the instance (location code).",
				MarkdownDescription: "The name of the instance (location code).",
			},
		},
	}
}

type DatabaseInstanceModel struct {
	DatabaseName types.String  `tfsdk:"database_name"`
	Instance     InstanceValue `tfsdk:"instance"`
	InstanceName types.String  `tfsdk:"instance_name"`
}

var _ basetypes.ObjectTypable = InstanceType{}

type InstanceType struct {
	basetypes.ObjectType
}

func (t InstanceType) Equal(o attr.Type) bool {
	other, ok := o.(InstanceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t InstanceType) String() string {
	return "InstanceType"
}

func (t InstanceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return nil, diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return nil, diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return nil, diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return InstanceValue{
		Hostname:     hostnameVal,
		Name:         nameVal,
		Region:       regionVal,
		InstanceType: typeVal,
		Uuid:         uuidVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewInstanceValueNull() InstanceValue {
	return InstanceValue{
		state: attr.ValueStateNull,
	}
}

func NewInstanceValueUnknown() InstanceValue {
	return InstanceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewInstanceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (InstanceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing InstanceValue Attribute Value",
				"While creating a InstanceValue value, a missing attribute value was detected. "+
					"A InstanceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InstanceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid InstanceValue Attribute Type",
				"While creating a InstanceValue value, an invalid attribute value was detected. "+
					"A InstanceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InstanceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("InstanceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra InstanceValue Attribute Value",
				"While creating a InstanceValue value, an extra attribute value was detected. "+
					"A InstanceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra InstanceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewInstanceValueUnknown(), diags
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	uuidAttribute, ok := attributes["uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uuid is missing from object`)

		return NewInstanceValueUnknown(), diags
	}

	uuidVal, ok := uuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uuid expected to be basetypes.StringValue, was: %T`, uuidAttribute))
	}

	if diags.HasError() {
		return NewInstanceValueUnknown(), diags
	}

	return InstanceValue{
		Hostname:     hostnameVal,
		Name:         nameVal,
		Region:       regionVal,
		InstanceType: typeVal,
		Uuid:         uuidVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewInstanceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) InstanceValue {
	object, diags := NewInstanceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewInstanceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t InstanceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewInstanceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewInstanceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewInstanceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewInstanceValueMust(InstanceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t InstanceType) ValueType(ctx context.Context) attr.Value {
	return InstanceValue{}
}

var _ basetypes.ObjectValuable = InstanceValue{}

type InstanceValue struct {
	Hostname     basetypes.StringValue `tfsdk:"hostname"`
	Name         basetypes.StringValue `tfsdk:"name"`
	Region       basetypes.StringValue `tfsdk:"region"`
	InstanceType basetypes.StringValue `tfsdk:"type"`
	Uuid         basetypes.StringValue `tfsdk:"uuid"`
	state        attr.ValueState
}

func (v InstanceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["hostname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Hostname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hostname"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Region.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region"] = val

		val, err = v.InstanceType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.Uuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v InstanceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v InstanceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v InstanceValue) String() string {
	return "InstanceValue"
}

func (v InstanceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"hostname": basetypes.StringType{},
		"name":     basetypes.StringType{},
		"region":   basetypes.StringType{},
		"type":     basetypes.StringType{},
		"uuid":     basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"hostname": v.Hostname,
			"name":     v.Name,
			"region":   v.Region,
			"type":     v.InstanceType,
			"uuid":     v.Uuid,
		})

	return objVal, diags
}

func (v InstanceValue) Equal(o attr.Value) bool {
	other, ok := o.(InstanceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Hostname.Equal(other.Hostname) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Region.Equal(other.Region) {
		return false
	}

	if !v.InstanceType.Equal(other.InstanceType) {
		return false
	}

	if !v.Uuid.Equal(other.Uuid) {
		return false
	}

	return true
}

func (v InstanceValue) Type(ctx context.Context) attr.Type {
	return InstanceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v InstanceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"hostname": basetypes.StringType{},
		"name":     basetypes.StringType{},
		"region":   basetypes.StringType{},
		"type":     basetypes.StringType{},
		"uuid":     basetypes.StringType{},
	}
}
