// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_database_config

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DatabaseConfigResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_attach": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Allow or disallow attaching databases to the current database.",
				MarkdownDescription: "Allow or disallow attaching databases to the current database.",
			},
			"block_reads": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Block all database reads.",
				MarkdownDescription: "Block all database reads.",
			},
			"block_writes": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Block all database writes.",
				MarkdownDescription: "Block all database writes.",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the database.",
				MarkdownDescription: "The name of the database.",
			},
			"size_limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.",
				MarkdownDescription: "The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.",
			},
		},
	}
}

type DatabaseConfigModel struct {
	AllowAttach types.Bool   `tfsdk:"allow_attach"`
	BlockReads  types.Bool   `tfsdk:"block_reads"`
	BlockWrites types.Bool   `tfsdk:"block_writes"`
	Id          types.String `tfsdk:"id"`
	SizeLimit   types.String `tfsdk:"size_limit"`
}
