// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_locations

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func LocationsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"locations": schema.MapAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "A mapping of location codes to location names.",
				MarkdownDescription: "A mapping of location codes to location names.",
			},
		},
	}
}

type LocationsModel struct {
	Locations types.Map `tfsdk:"locations"`
}
